name: Deploy Aplication Test

on:
  push:
    branches: [pipeline]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hospital-care-api.jar
          path: build/libs/hospital-care-api.jar

  deploy:
    runs-on: self-hosted       
    needs: build 
    steps:
      - name: Check if artifact exists
        run: |
          if exist "D:\Unidac\hospital-care-api.jar" (
            echo "Arquivo JAR não encontrado. Iniciando download."
            exit 1
          ) else (
            echo "Arquivo JAR encontrado. Abortando  download..."
            exit 0
          )
        shell: cmd
      - name: Baixar WinSW
        run: |
            Invoke-WebRequest -Uri "https://github.com/winsw/winsw/releases/latest/download/winsw.exe" -OutFile "winsw.exe"
      - name: Download Artifact
        if: success()
        uses: actions/download-artifact@v2
        with:
          name: hospital-care-api.jar
          path: D:\Unidac
      