name: Deploy Aplication Test

on:
  push:
    branches: [pipeline]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-jar
          path: build/libs/hospital-care-api.jar

  deploy:
    runs-on: self-hosted       
    needs: build 
    steps:
       - name: Download Artifact
         uses: actions/download-artifact@v2
         with:
            name: hospital-care.jar
            path: /home/runner/work/template-api/template-api/build/libs/hospital-care-api.jar